dist: xenial
language: python
notifications:
  email: false
python:
  - "2.7"
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
sudo: false
install:
  - python setup.py install
script:
  # test import
  - python -c 'import urecon'
#deploy:
#  provider: pypi
#  user: s4w3d0ff
#  password:
#    secure:
#  on:
#    tags: true
#  skip_existing: true
